- get_url: url="https://ftp.postgresql.org/pub/source/v{{postgresql_source_build}}/postgresql-{{postgresql_source_build}}.tar.gz" dest=/tmp/postgresql.tar.gz
- unarchive: src=/tmp/postgresql.tar.gz dest=/tmp
- shell: ./configure --with-systemd --prefix=/usr/lib/postgresql/{{postgresql_version}} --sysconfdir={{postgresql_config_path}} --bindir={{postgresql_bin_path}} chdir=/tmp/postgresql-{{postgresql_source_build}}
- shell: make chdir=/tmp/postgresql-{{postgresql_source_build}}
- shell: make install chdir=/tmp/postgresql-{{postgresql_source_build}}
- copy: src=postgresql.service dest=/lib/systemd/system/postgresql.service
- copy: src=postgresql@.service dest=/lib/systemd/system/postgresql@.service
- copy: src=postgresql.init dest=/etc/init.d/postgresql mode=u=rwx,g=rx,o=rx

- name: Enable service
  service:
    name: postgresql
    enabled: yes