- get_url: url="https://ftp.postgresql.org/pub/source/v{{postgresql_source_build}}/postgresql-{{postgresql_source_build}}.tar.gz" dest=/tmp/postgresql.tar.gz
- unarchive: src=/tmp/postgresql.tar.gz dest=/tmp
- shell: ./configure chdir=/tmp/postgresql-{{postgresql_source_build}}
- shell: make chdir=/tmp/postgresql-{{postgresql_source_build}}
- shell: make install chdir=/tmp/postgresql-{{postgresql_source_build}}