- get_url: url="https://ftp.postgresql.org/pub/source/v{{postgresql_source_build}}/postgresql-{{postgresql_source_build}}.tar.gz" dest=/tmp/postgresql.tar.gz
  when: 'postgresql_config_only == False'
- unarchive: src=/tmp/postgresql.tar.gz dest=/tmp
  when: 'postgresql_config_only == False'
- shell: ./configure --with-systemd --prefix=/usr/lib/postgresql/{{postgresql_version}} --sysconfdir={{postgresql_config_path}} --bindir={{postgresql_bin_path}} {{postgresql_additional_configure}} chdir=/tmp/postgresql-{{postgresql_source_build}}
  when: 'postgresql_config_only == False'
- shell: make {{postgresql_additional_make}} chdir=/tmp/postgresql-{{postgresql_source_build}}
  when: 'postgresql_config_only == False'
- shell: make install chdir=/tmp/postgresql-{{postgresql_source_build}}
  when: 'postgresql_config_only == False'
- copy: src=postgresql.service dest=/lib/systemd/system/postgresql.service
- copy: src=postgresql@.service dest=/lib/systemd/system/postgresql@.service
- copy: src=postgresql.init dest=/etc/init.d/postgresql mode=u=rwx,g=rx,o=rx
- copy: src=pg_ctlcluster dest=/usr/bin/pg_ctlcluster mode=u=rwx,g=rx,o=rx
- file: src=/usr/lib/postgresql/{{postgresql_version}}/bin/pg_config dest=/usr/bin/pg_config state=link
- file: src=/usr/lib/postgresql/{{postgresql_version}}/bin/psql dest=/usr/bin/psql state=link
- copy: src=PgCommon.pm dest=/etc/perl/PgCommon.pm mode=u=rwx,g=rx,o=rx

- name: Enable service
  service:
    name: postgresql
    enabled: yes
