---
# Variable configuration.
- include: variables.yml

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat' and postgresql_config_only == False

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: initialize.yml
- include: configure.yml

- name: Ensure PostgreSQL is started and enabled on boot.
  shell: systemctl enable "{{ postgresql_daemon }}"

# Configure PostgreSQL.
- include: databases.yml
- include: users.yml
