---
- name: Ensure PostgreSQL Python libraries are installed.
  apt:
    name: "{{ postgresql_python_library }}"
    state: installed
  where: 'postgresql_python_library != ""'

- name: Ensure PostgreSQL packages are installed.
  apt:
    name: "{{ item }}"
    state: installed
  with_items: "{{ postgresql_packages }}"
  where: 'postgresql_source_build == False'

- name: Ensure PostgreSQL build dependencies are installed.
  apt:
    name: "{{ item }}"
    state: installed
  with_items: "{{ postgresql_build_dependencies }}"
  where: 'postgresql_source_build'

- name: Ensure all configured locales are present.
  locale_gen: "name={{ item }} state=present"
  with_items: "{{ postgresql_locales }}"
  register: locale_gen_result

- name: Force-restart PostgreSQL after new locales are generated.
  service:
    name: "{{ postgresql_daemon }}"
    state: restarted
  when: locale_gen_result.changed

- name: Execute PostgreSQL build
  include: build-source.yml
  where: 'postgresql_source_build'